# BovIA — comandos de desenvolvimento
# Uso: `make` para listar os targets, `make dev` para rodar tudo

.PHONY: help dev backend frontend install migrate migration tsc build clean

# venv do backend (assume backend/venv/ ja criado)
PY := backend/venv/bin/python
PIP := backend/venv/bin/pip
UVICORN := backend/venv/bin/uvicorn
ALEMBIC := backend/venv/bin/alembic

help:
	@echo "BovIA — comandos disponiveis:"
	@echo ""
	@echo "  make dev          Roda backend + frontend juntos (Ctrl+C para parar ambos)"
	@echo "  make backend      So o backend (porta 8000, reload automatico)"
	@echo "  make frontend     So o frontend (porta 5173, HMR automatico)"
	@echo ""
	@echo "  make install      Instala deps do backend (venv) e do frontend (npm)"
	@echo "  make migrate      Aplica todas as migrations pendentes"
	@echo "  make migration name=mensagem    Cria nova migration autogenerated"
	@echo "  make tsc          Type-check do frontend (sem gerar build)"
	@echo "  make build        Build de producao do frontend"
	@echo ""

backend:
	cd backend && ../$(UVICORN) app.main:app --reload --port 8000

frontend:
	cd frontend && npm run dev

# Roda os dois em paralelo com prefixo de log e Ctrl+C limpo
dev:
	@trap 'kill 0' INT TERM; \
	( $(MAKE) backend  2>&1 | sed -l -e 's/^/[BE] /' ) & \
	( $(MAKE) frontend 2>&1 | sed -l -e 's/^/[FE] /' ) & \
	wait

install:
	cd backend && $(PIP) install -r requirements.txt
	cd frontend && npm install

migrate:
	cd backend && ../$(ALEMBIC) upgrade head

# Uso: make migration name="adicionar campo X em Y"
migration:
	@if [ -z "$(name)" ]; then echo "Uso: make migration name=\"descricao\""; exit 1; fi
	cd backend && ../$(ALEMBIC) revision --autogenerate -m "$(name)"

tsc:
	cd frontend && npx tsc --noEmit

build:
	cd frontend && npm run build

clean:
	@echo "Matando processos uvicorn e vite..."
	@pkill -f 'uvicorn app.main:app' 2>/dev/null || true
	@pkill -f 'vite' 2>/dev/null || true
