"""campos_assinatura_user

Revision ID: 76e03a9d28d5
Revises: f4b07c812a9e
Create Date: 2026-06-10 21:28:31.780110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e03a9d28d5'
down_revision: Union[str, None] = 'f4b07c812a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('gratuito', 'bronze', 'prata', 'ouro', name='planoenum').create(op.get_bind())
    sa.Enum('ativo', 'inadimplente', 'cancelado', 'expirado', name='assinaturastatusenum').create(op.get_bind())
    op.add_column('users', sa.Column('plano', sa.Enum('gratuito', 'bronze', 'prata', 'ouro', name='planoenum'), nullable=True))
    op.add_column('users', sa.Column('assinatura_status', sa.Enum('ativo', 'inadimplente', 'cancelado', 'expirado', name='assinaturastatusenum'), nullable=True))
    op.add_column('users', sa.Column('assinatura_expira_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'assinatura_expira_em')
    op.drop_column('users', 'assinatura_status')
    op.drop_column('users', 'plano')
    sa.Enum(name='assinaturastatusenum').drop(op.get_bind())
    sa.Enum(name='planoenum').drop(op.get_bind())
    # ### end Alembic commands ###

