"""estado_inicial_todas_tabelas

Revision ID: f24ce695144b
Revises: 
Create Date: 2026-04-05 23:37:01.278168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24ce695144b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotes', sa.Column('rendimento_carcaca', sa.Float(), nullable=True))
    op.add_column('movimentacoes', sa.Column('preco_arroba', sa.Float(), nullable=True))
    op.add_column('movimentacoes', sa.Column('agio_compra', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimentacoes', 'agio_compra')
    op.drop_column('movimentacoes', 'preco_arroba')
    op.drop_column('lotes', 'rendimento_carcaca')
    # ### end Alembic commands ###
